//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user
    {
        [Key]
        public int u_id { get; set; }
        [Display(Name ="Full Name")]
        [Required(ErrorMessage = "Full Name is required!")]
        public string u_name { get; set; }
        [Display(Name = "User Name")]
        [Required(ErrorMessage = "User Name is required!")]
        public string u_username { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Password is required!")]
        public string u_password { get; set; }
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Phone Number is required!")]
        public string u_phone { get; set; }
        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Email Address is required!")]
        public string u_email { get; set; }
        [Display(Name = "Status")]
        [Required(ErrorMessage = "Status is required!")]
        public string u_status { get; set; }
        public int r_id { get; set; }
    
        public virtual role role { get; set; }
    }
}
